version: '3.4'

services:
  movieapp:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+:443;http://+:80
    container_name: backendapi_container
    ports:
      - "8020:80"
      - "8021:443"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro
  sqldb:
    image: mcr.microsoft.com/mssql/server:latest
    container_name: mssgl_container
    environment:
        - SA_PASSWORD=Sa123456
        - ACCEPT_EULA=Y
    ports:
      - "1440:1433"
  mymovies:
    build:
      context: .
      dockerfile: mymovies/Dockerfile
    volumes:
      - ./:/app
    ports:
      - "3000:3000"
    image: app/react
    container_name: frontend_container
    command: npm start
